*******************************************************************************
****** nor1x schematic nor1x  <vs>  nor1x layout nor1x
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45n1svt) MOS                                    2       2
(g45p1svt) MOS                                    2       2
                                             ------  ------
Total                                             4       4

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    2       2           0       0
(g45p1svt) MOS                                    2       2           0       0
(g45n1svt:ParMos2#1) MosBlk                       -       -           1       1
(g45p1svt:SerMos2#1) MosBlk                       -       -           1       1
                                             ------  ------      ------  ------
Total                                             4       4           2       2

Schematic and Layout Match
