*******************************************************************************
****** xnor schematic xnor  <vs>  xnor layout xnor
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45n1svt) MOS                                    7       7
(g45p1svt) MOS                                    7       7
                                             ------  ------
Total                                            14      14

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    7       7           3       3
(g45p1svt) MOS                                    7       7           3       3
(g45n1svt:SerMos2#1) MosBlk                       -       -           2       2
(g45p1svt:ParMos2#1) MosBlk                       -       -           2       2
(g45p1svt:SerMos4#1) MosBlk                       -       -           1       1
                                             ------  ------      ------  ------
Total                                            14      14          11      11

Schematic and Layout Match
