*******************************************************************************
****** hafl_adder1x schematic half_adder  <vs>  hafl_adder1x layout half_adder
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45n1svt) MOS                                    9       9
(g45p1svt) MOS                                    9       9
                                             ------  ------
Total                                            18      18

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    9       9           3       3
(g45p1svt) MOS                                    9       9           3       3
(g45n1svt:SerMos2#1) MosBlk                       -       -           3       3
(g45p1svt:ParMos2#1) MosBlk                       -       -           3       3
(g45p1svt:SerMos4#1) MosBlk                       -       -           1       1
                                             ------  ------      ------  ------
Total                                            18      18          13      13

Schematic and Layout Match
