*******************************************************************************
****** xor1x schematic xor  <vs>  xor1x layout xor
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45n1svt) MOS                                    6       6
(g45p1svt) MOS                                    6       6
                                             ------  ------
Total                                            12      12

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    6       6           2       2
(g45p1svt) MOS                                    6       6           2       2
(g45n1svt:SerMos2#1) MosBlk                       -       -           2       2
(g45p1svt:ParMos2#1) MosBlk                       -       -           2       2
(g45p1svt:SerMos4#1) MosBlk                       -       -           1       1
                                             ------  ------      ------  ------
Total                                            12      12           9       9

Schematic and Layout Match
