*******************************************************************************
****** add1x schematic add1x  <vs>  add1x layout add1x
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45n1svt) MOS                                    3       3
(g45p1svt) MOS                                    3       3
                                             ------  ------
Total                                             6       6

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    3       3           1       1
(g45p1svt) MOS                                    3       3           1       1
(g45n1svt:SerMos2#1) MosBlk                       -       -           1       1
(g45p1svt:ParMos2#1) MosBlk                       -       -           1       1
                                             ------  ------      ------  ------
Total                                             6       6           4       4

Schematic and Layout Match
