*******************************************************************************
****** d_latch1 schematic d_latch1  <vs>  d_latch1 layout d_latch1
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45n1svt) MOS                                    9       9
(g45p1svt) MOS                                    9       9
                                             ------  ------
Total                                            18      18

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    9       9           1       1
(g45p1svt) MOS                                    9       9           1       1
(g45n1svt:SerMos2#1) MosBlk                       -       -           4       4
(g45p1svt:ParMos2#1) MosBlk                       -       -           4       4
                                             ------  ------      ------  ------
Total                                            18      18          10      10

Schematic and Layout Match
