*******************************************************************************
****** sr schematic sr  <vs>  sr layout sr
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45n1svt) MOS                                    8       8
(g45p1svt) MOS                                    8       8
                                             ------  ------
Total                                            16      16

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    8       8           0       0
(g45p1svt) MOS                                    8       8           0       0
(g45n1svt:SerMos2#1) MosBlk                       -       -           4       4
(g45p1svt:ParMos2#1) MosBlk                       -       -           4       4
                                             ------  ------      ------  ------
Total                                            16      16           8       8

Schematic and Layout Match
